[font]
size = 14 

[font.normal]
# family = "Consolas" 
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
opacity = 0.92

[window.padding]
x = 7
y = 2

[general]
import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

